# Core
- Amount
- DonorEmail
- DonorFullName
- AmountInCents
- StreetAddress

# WorldPay
- WorldpayAccountName
- WorldpayCurrency
- WorldpayEmail
- WorldpayMethodCodec
- WorldpayNarrativeStatement
- WorldpayReturnto
- WorldpayRoutingInfo

# Keep the Mangler at the end, as it transcodes all staged data
- EncodingMangler
