visa:
    countries:
        US: true
        IL: true
        FR: true
    group: cc
    validation:
        name: true
        email: true
        amount: true
    logo: card-visa.png
amex:
    countries:
        US: true
        IL: true
        FR: true
    group: cc
    validation:
        name: true
        email: true
        amount: true
    logo: card-amex.png
mc:
    countries:
        US: true
        IL: true
        FR: true
    group: cc
    validation:
        name: true
        email: true
        amount: true
    logo: card-mc.png
discover:
    countries:
        US: true
        IL: true
    group: cc
    validation:
        name: true
        email: true
        amount: true
    logo: card-discover.png

